server:
  port: 9001

app:
  swagger:
    info:
      # http://localhost:9001/swagger-ui/index.html
      description: "This is a REST interface to a simple lottery system."
      version: "1.0.0"
      title: "Swagger Lottery System"
      termsOfService: "http://swagger.io/terms/"
      contact:
        email: "hongyuan.han0518@gmail.com"
      license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"

spring:
  profiles:
    active: "dev"

---

spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    # http://localhost:9001/h2-console
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---

spring:
  config.activate.on-profile: uat
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false


logging:
  level:
    com.poppulo.interview: INFO